language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
jdk:
  - oraclejdk8
script: 
         - cd clarityviews
         - mvn clean package assembly:single deploy --settings settings.xml -Dmaven.test.skip=true 
